export enum TicketHistoryActionEnum {
    TICKET_CRIADO = "TICKET_CRIADO",
    STATUS_ALTERADO = "STATUS_ALTERADO",
    RESPONSAVEL_ALTERADO = "RESPONSAVEL_ALTERADO",
    COMENTARIO_ADICIONADO = "COMENTARIO_ADICIONADO"
}
