export enum TicketHistoryActionEnum {
    TICKET_CRIADO = "TICKET_CRIADO",
    STATUS_ALTERADO = "STATUS_ALTERADO",
    RESPONSAVEL_ALTERADO = "RESPONSAVEL_ALTERADO",
    TITULO_ALTERADO = "TITULO_ALTERADO",
    DESCRICAO_ALTERADA = "DESCRICAO_ALTERADA",
    PRIORIDADE_ALTERADA = "PRIORIDADE_ALTERADA",
    COMENTARIO_ADICIONADO = "COMENTARIO_ADICIONADO"
}
